# test_large_file_generation.py
# GAP-LGF-1: Large File Generation — Mandatory Chunking Protocol
#
# Tests Rule LGF-1 from .clinerules: When generating files >500 lines,
# the agent MUST use chunked generation (400-500 line chunks) + PowerShell
# pipeline assembly.
#
# Reference: .clinerules lines 352-397
#
# Chunking is NOT required for:
# - Files generated by build tools (pytest --collect-only, pip freeze)
# - Output streamed incrementally (long-running dev servers)
# - Append operations to existing files

import json
import os
import subprocess
from pathlib import Path

import pytest


class TestChunkingThreshold:
    # =================================================================
    # LGF-1: Threshold Detection
    # =================================================================

    def test_lgf001_chunking_triggered_at_500_lines(self, tmp_path):
        # LGF-001: Chunking protocol triggered when file > 500 lines
        large_file = tmp_path / 'large_spec.md'
        
        # Create a 501-line file
        lines = ['# Large Specification Document\n']
        for i in range(500):
            lines.append(f'## Section {i}\nContent for section {i}.\n')
        
        large_file.write_text(''.join(lines), encoding='utf-8')
        
        # Verify file exceeds threshold
        content = large_file.read_text(encoding='utf-8')
        line_count = len(content.splitlines())
        assert line_count > 500, f'File has {line_count} lines, threshold is 500'

    def test_lgf002_no_chunking_under_500_lines(self, tmp_path):
        # LGF-002: Single write allowed for files < 500 lines
        small_file = tmp_path / 'small_spec.md'
        
        # Create a ~400-line file (under threshold)
        # Each iteration adds 1 line, so range(400) gives exactly 400 lines
        lines = ['# Small Specification\n']
        for i in range(399):
            lines.append(f'## Section {i}\n')
        
        small_file.write_text(''.join(lines), encoding='utf-8')
        
        # This should NOT trigger chunking — single write is fine
        content = small_file.read_text(encoding='utf-8')
        line_count = len(content.splitlines())
        assert line_count < 500

    def test_lgf003_exactly_500_lines_edge_case(self, tmp_path):
        # LGF-003: Exactly 500 lines — at threshold, single write OK
        edge_file = tmp_path / 'edge_spec.md'
        
        # Create exactly 500 lines (1 header + 499 content lines)
        lines = ['# Specification\n']
        for i in range(499):
            lines.append(f'## Section {i}\n')
        
        edge_file.write_text(''.join(lines), encoding='utf-8')
        
        content = edge_file.read_text(encoding='utf-8')
        line_count = len(content.splitlines())
        # Exactly 500 is the threshold — single write should be acceptable
        assert line_count == 500


class TestChunkingProtocol:
    # =================================================================
    # LGF-1: Chunking Protocol Compliance
    # =================================================================

    def test_lgf004_chunk_size_400_to_500_lines(self, tmp_path):
        # LGF-004: Each chunk should be 400-500 lines
        chunks = []
        
        # Create first chunk (500 lines)
        chunk1 = tmp_path / '_temp_chunk_01.md'
        lines1 = ['# Part 1\n']
        for i in range(499):
            lines1.append(f'Line {i}\n')
        chunk1.write_text(''.join(lines1), encoding='utf-8')
        chunks.append(chunk1)
        
        # Create second chunk (400 lines)
        chunk2 = tmp_path / '_temp_chunk_02.md'
        lines2 = ['# Part 2\n']
        for i in range(399):
            lines2.append(f'Line {i}\n')
        chunk2.write_text(''.join(lines2), encoding='utf-8')
        chunks.append(chunk2)
        
        # Verify chunk sizes
        for chunk in chunks:
            content = chunk.read_text(encoding='utf-8')
            line_count = len(content.splitlines())
            assert 400 <= line_count <= 500, f'Chunk has {line_count} lines, expected 400-500'

    def test_lgf005_temp_chunks_written_before_assembly(self, tmp_path):
        # LGF-005: Verify temp chunk files are created before assembly
        chunk1 = tmp_path / '_temp_chunk_01.md'
        chunk2 = tmp_path / '_temp_chunk_02.md'
        
        chunk1.write_text('# Part 1\n' + 'Line\n' * 500, encoding='utf-8')
        chunk2.write_text('# Part 2\n' + 'Line\n' * 400, encoding='utf-8')
        
        # Both chunks must exist before assembly
        assert chunk1.exists(), 'Chunk 1 must exist before assembly'
        assert chunk2.exists(), 'Chunk 2 must exist before assembly'

    def test_lgf006_assembly_uses_pipeline_pattern(self, tmp_path):
        # LGF-006: Assembly uses PowerShell pipeline pattern
        # Pattern: Get-Content chunk1, chunk2 | Set-Content target -Encoding UTF8
        
        chunk1 = tmp_path / '_temp_chunk_01.md'
        chunk2 = tmp_path / '_temp_chunk_02.md'
        target = tmp_path / 'assembled.md'
        
        chunk1.write_text('# Part 1\n' + 'Line\n' * 500, encoding='utf-8')
        chunk2.write_text('# Part 2\n' + 'Line\n' * 400, encoding='utf-8')
        
        # Windows pipeline assembly
        if os.name == 'nt':  # Windows
            cmd = f'Get-Content {chunk1}, {chunk2} | Set-Content {target} -Encoding UTF8'
            subprocess.run(cmd, shell=True, cwd=str(tmp_path), capture_output=True)
        else:  # Unix - use cat
            subprocess.run(f'cat {chunk1} {chunk2} > {target}', shell=True, cwd=str(tmp_path))
        
        # Verify assembled file
        assert target.exists(), 'Assembled file must exist'
        content = target.read_text(encoding='utf-8')
        line_count = len(content.splitlines())
        assert line_count == 901, f'Assembled file has {line_count} lines'


class TestChunkingExceptions:
    # =================================================================
    # LGF-1: Exceptions to Chunking Requirement
    # =================================================================

    def test_lgf007_build_tool_output_exempt(self, tmp_path, monkeypatch):
        # LGF-007: Files generated by build tools are exempt from chunking
        # e.g., pytest --collect-only, pip freeze
        
        # Simulate build tool output
        build_output = tmp_path / 'requirements.txt'
        output_lines = ['Package1==1.0.0\n'] * 100
        build_output.write_text(''.join(output_lines), encoding='utf-8')
        
        # Verify this doesn't need chunking even if >500 lines
        content = build_output.read_text(encoding='utf-8')
        # Build tools stream output, so chunking doesn't apply

    def test_lgf008_streamed_output_exempt(self, tmp_path):
        # LGF-008: Long-running dev server output is exempt
        # This is an append scenario
        
        log_file = tmp_path / 'dev_server.log'
        log_file.write_text('# Dev Server Log\n', encoding='utf-8')
        
        # Simulate appending log entries
        for i in range(600):
            log_file.write_text(f'[INFO] Log entry {i}\n', encoding='utf-8')
        
        # Append mode doesn't require chunking
        content = log_file.read_text(encoding='utf-8')
        line_count = len(content.splitlines())
        assert line_count > 500

    def test_lgf009_append_to_existing_exempt(self, tmp_path):
        # LGF-009: Appending to existing file is exempt
        existing = tmp_path / 'existing.md'
        existing.write_text('# Existing Document\n' + 'Content\n' * 100, encoding='utf-8')
        
        # Append new section
        with open(existing, 'a', encoding='utf-8') as f:
            for i in range(500):
                f.write(f'## Added Section {i}\n')
        
        # Append operations don't need chunking
        content = existing.read_text(encoding='utf-8')
        line_count = len(content.splitlines())
        assert line_count > 500


class TestChunkingCleanup:
    # =================================================================
    # LGF-1: Temp File Cleanup
    # =================================================================

    def test_lgf010_temp_chunks_deleted_after_assembly(self, tmp_path):
        # LGF-010: _temp_chunk_*.md files must be deleted after assembly
        chunk1 = tmp_path / '_temp_chunk_01.md'
        chunk2 = tmp_path / '_temp_chunk_02.md'
        target = tmp_path / 'assembled.md'
        
        # Write chunks
        chunk1.write_text('# Part 1\n' + 'Line\n' * 500, encoding='utf-8')
        chunk2.write_text('# Part 2\n' + 'Line\n' * 400, encoding='utf-8')
        
        # Simulate assembly
        if os.name == 'nt':
            cmd = f'Get-Content {chunk1}, {chunk2} | Set-Content {target} -Encoding UTF8'
            subprocess.run(cmd, shell=True, cwd=str(tmp_path), capture_output=True)
        else:
            subprocess.run(f'cat {chunk1} {chunk2} > {target}', shell=True, cwd=str(tmp_path))
        
        # Delete temp chunks
        chunk1.unlink()
        chunk2.unlink()
        
        # Verify cleanup
        assert not chunk1.exists(), 'Chunk 1 must be deleted'
        assert not chunk2.exists(), 'Chunk 2 must be deleted'
        assert target.exists(), 'Target file must exist'

    def test_lgf011_failed_assembly_leaves_chunks_for_debug(self, tmp_path):
        # LGF-011: If assembly fails, chunks should remain for debugging
        chunk1 = tmp_path / '_temp_chunk_01.md'
        chunk2 = tmp_path / '_temp_chunk_02.md'
        
        chunk1.write_text('# Part 1\n' + 'Line\n' * 500, encoding='utf-8')
        chunk2.write_text('# Part 2\n' + 'Line\n' * 400, encoding='utf-8')
        
        # Simulate failed assembly (target never created)
        # Chunks should remain for manual recovery


class TestVerification:
    # =================================================================
    # LGF-1: Line Count Verification
    # =================================================================

    def test_lgf012_assembled_line_count_matches_sum(self, tmp_path):
        # LGF-012: Assembled file line count = sum of chunk line counts
        chunk1 = tmp_path / '_temp_chunk_01.md'
        chunk2 = tmp_path / '_temp_chunk_02.md'
        target = tmp_path / 'assembled.md'
        
        # 500 lines
        chunk1.write_text('# Part 1\n' + 'Line\n' * 499, encoding='utf-8')
        # 400 lines
        chunk2.write_text('# Part 2\n' + 'Line\n' * 399, encoding='utf-8')
        
        # Assemble
        if os.name == 'nt':
            cmd = f'Get-Content {chunk1}, {chunk2} | Set-Content {target} -Encoding UTF8'
            subprocess.run(cmd, shell=True, cwd=str(tmp_path), capture_output=True)
        else:
            subprocess.run(f'cat {chunk1} {chunk2} > {target}', shell=True, cwd=str(tmp_path))
        
        # Verify
        target_content = target.read_text(encoding='utf-8')
        chunk1_content = chunk1.read_text(encoding='utf-8')
        chunk2_content = chunk2.read_text(encoding='utf-8')
        
        target_lines = len(target_content.splitlines())
        chunk1_lines = len(chunk1_content.splitlines())
        chunk2_lines = len(chunk2_content.splitlines())
        
        assert target_lines == chunk1_lines + chunk2_lines

    def test_lgf013_spot_check_content_preserved(self, tmp_path):
        # LGF-013: Verify content integrity after assembly
        chunk1 = tmp_path / '_temp_chunk_01.md'
        chunk2 = tmp_path / '_temp_chunk_02.md'
        target = tmp_path / 'assembled.md'
        
        marker1 = '=== UNIQUE MARKER 1 ==='
        marker2 = '=== UNIQUE MARKER 2 ==='
        
        chunk1.write_text(f'# Part 1\n{marker1}\n' + 'Line\n' * 498, encoding='utf-8')
        chunk2.write_text(f'# Part 2\n{marker2}\n' + 'Line\n' * 398, encoding='utf-8')
        
        # Assemble
        if os.name == 'nt':
            cmd = f'Get-Content {chunk1}, {chunk2} | Set-Content {target} -Encoding UTF8'
            subprocess.run(cmd, shell=True, cwd=str(tmp_path), capture_output=True)
        else:
            subprocess.run(f'cat {chunk1} {chunk2} > {target}', shell=True, cwd=str(tmp_path))
        
        # Verify markers preserved
        content = target.read_text(encoding='utf-8')
        assert marker1 in content, 'Marker 1 must be preserved'
        assert marker2 in content, 'Marker 2 must be preserved'


class TestForbiddenPattern:
    # =================================================================
    # LGF-1: Forbidden Concatenation Pattern
    # =================================================================

    def test_lgf014_inline_addition_forbidden(self, tmp_path):
        # LGF-014: Inline addition pattern is FORBIDDEN
        # Forbidden: (Get-Content a) + (Get-Content b)
        
        file_a = tmp_path / 'file_a.md'
        file_b = tmp_path / 'file_b.md'
        target = tmp_path / 'target.md'
        
        file_a.write_text('# File A\n' + 'Line\n' * 250, encoding='utf-8')
        file_b.write_text('# File B\n' + 'Line\n' * 250, encoding='utf-8')
        
        # This is the FORBIDDEN pattern (inline addition)
        # content = file_a.read_text() + file_b.read_text()  # DON'T DO THIS
        
        # Correct pattern uses pipeline
        if os.name == 'nt':
            cmd = f'Get-Content {file_a}, {file_b} | Set-Content {target} -Encoding UTF8'
            subprocess.run(cmd, shell=True, cwd=str(tmp_path), capture_output=True)
        else:
            subprocess.run(f'cat {file_a} {file_b} > {target}', shell=True, cwd=str(tmp_path))
        
        # Verify result
        assert target.exists()